/**
 * Gallery Manifest
 *
 * Auto-generated file containing all gallery images and metadata.
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * Generated: 2026-01-16T22:15:29.057Z
 * Total Images: 86
 */

export interface GalleryImage {
  src: string;
  alt: string;
  category: string;
  project?: string | null;
  fileName: string;
}

export interface GalleryCategory {
  name: string;
  count: number;
  heroImage: string;
}

export interface GalleryManifest {
  images: GalleryImage[];
  categories: GalleryCategory[];
  totalImages: number;
  generatedAt: string;
}

export const galleryManifest: GalleryManifest = {
  "images": [
    {
      "src": "/images/gallery/Bedroom/professional-wood-interiors-bedroom-remodel-01.png",
      "alt": "Custom bedroom built-in cabinetry with professional wood interiors bedroom remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bedrooms",
      "project": null,
      "fileName": "professional-wood-interiors-bedroom-remodel-01.png"
    },
    {
      "src": "/images/gallery/Bedroom/professional-wood-interiors-bedroom-remodel-02.png",
      "alt": "Custom bedroom built-in cabinetry with professional wood interiors bedroom remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bedrooms",
      "project": null,
      "fileName": "professional-wood-interiors-bedroom-remodel-02.png"
    },
    {
      "src": "/images/gallery/Bedroom/professional-wood-interiors-bedroom-remodel-03.png",
      "alt": "Custom bedroom built-in cabinetry with professional wood interiors bedroom remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bedrooms",
      "project": null,
      "fileName": "professional-wood-interiors-bedroom-remodel-03.png"
    },
    {
      "src": "/images/gallery/Bedroom/professional-wood-interiors-bedroom-remodel-04.png",
      "alt": "Custom bedroom built-in cabinetry with professional wood interiors bedroom remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bedrooms",
      "project": null,
      "fileName": "professional-wood-interiors-bedroom-remodel-04.png"
    },
    {
      "src": "/images/gallery/Bedroom/professional-wood-interiors-bedroom-remodel-05.png",
      "alt": "Custom bedroom built-in cabinetry with professional wood interiors bedroom remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bedrooms",
      "project": null,
      "fileName": "professional-wood-interiors-bedroom-remodel-05.png"
    },
    {
      "src": "/images/gallery/Bedroom/professional-wood-interiors-bedroom-remodel-06.png",
      "alt": "Custom bedroom built-in cabinetry with professional wood interiors bedroom remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bedrooms",
      "project": null,
      "fileName": "professional-wood-interiors-bedroom-remodel-06.png"
    },
    {
      "src": "/images/gallery/Bookcases/white  bookcase remodel-02.jpg",
      "alt": "Custom built-in bookcase with white  bookcase remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bookcases",
      "project": null,
      "fileName": "white  bookcase remodel-02.jpg"
    },
    {
      "src": "/images/gallery/Bookcases/white  bookcase remodel-03.jpg",
      "alt": "Custom built-in bookcase with white  bookcase remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bookcases",
      "project": null,
      "fileName": "white  bookcase remodel-03.jpg"
    },
    {
      "src": "/images/gallery/Bookcases/white  bookcase remodel-04.jpg",
      "alt": "Custom built-in bookcase with white  bookcase remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bookcases",
      "project": null,
      "fileName": "white  bookcase remodel-04.jpg"
    },
    {
      "src": "/images/gallery/Entertainment Centers/entertainment-center-01.jpg",
      "alt": "Custom entertainment center and media cabinet featuring entertainment center by Professional Wood Interiors - St. Louis, MO",
      "category": "Entertainment Centers",
      "project": null,
      "fileName": "entertainment-center-01.jpg"
    },
    {
      "src": "/images/gallery/Entertainment Centers/entertainment-fireplace-remodel-01.jpg",
      "alt": "Custom entertainment center and media cabinet featuring entertainment fireplace remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Entertainment Centers",
      "project": null,
      "fileName": "entertainment-fireplace-remodel-01.jpg"
    },
    {
      "src": "/images/gallery/Entertainment Centers/entertainment-fireplace-remodel-02.jpg",
      "alt": "Custom entertainment center and media cabinet featuring entertainment fireplace remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Entertainment Centers",
      "project": null,
      "fileName": "entertainment-fireplace-remodel-02.jpg"
    },
    {
      "src": "/images/gallery/Entertainment Centers/full fireplace entertainment center remodel-01.jpg",
      "alt": "Custom entertainment center and media cabinet featuring full fireplace entertainment center remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Entertainment Centers",
      "project": null,
      "fileName": "full fireplace entertainment center remodel-01.jpg"
    },
    {
      "src": "/images/gallery/Entertainment Centers/full fireplace entertainment center remodel-02.jpg",
      "alt": "Custom entertainment center and media cabinet featuring full fireplace entertainment center remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Entertainment Centers",
      "project": null,
      "fileName": "full fireplace entertainment center remodel-02.jpg"
    },
    {
      "src": "/images/gallery/Entertainment Centers/full fireplace entertainment center remodel-03.jpg",
      "alt": "Custom entertainment center and media cabinet featuring full fireplace entertainment center remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Entertainment Centers",
      "project": null,
      "fileName": "full fireplace entertainment center remodel-03.jpg"
    },
    {
      "src": "/images/gallery/Entertainment Centers/full fireplace entertainment center remodel-04.jpg",
      "alt": "Custom entertainment center and media cabinet featuring full fireplace entertainment center remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Entertainment Centers",
      "project": null,
      "fileName": "full fireplace entertainment center remodel-04.jpg"
    },
    {
      "src": "/images/gallery/Entertainment Centers/full fireplace entertainment center remodel-05.jpg",
      "alt": "Custom entertainment center and media cabinet featuring full fireplace entertainment center remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Entertainment Centers",
      "project": null,
      "fileName": "full fireplace entertainment center remodel-05.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-01.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-01.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-02.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-02.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-03.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-03.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-04.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-04.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-05.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-05.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-06.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-06.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-07.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-07.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-08.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-08.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Blue Island/kitchen-remodel-blue-island-09.jpg",
      "alt": "Blue Island Kitchen Custom kitchen remodel featuring kitchen remodel blue island by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Blue Island Kitchen",
      "fileName": "kitchen-remodel-blue-island-09.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Darkwood/kitchen-darkwood-remodel-01.jpg",
      "alt": "Darkwood Kitchen Custom kitchen remodel featuring kitchen darkwood remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Darkwood Kitchen",
      "fileName": "kitchen-darkwood-remodel-01.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Darkwood/kitchen-darkwood-remodel-02.jpg",
      "alt": "Darkwood Kitchen Custom kitchen remodel featuring kitchen darkwood remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Darkwood Kitchen",
      "fileName": "kitchen-darkwood-remodel-02.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Darkwood/kitchen-darkwood-remodel-03.jpg",
      "alt": "Darkwood Kitchen Custom kitchen remodel featuring kitchen darkwood remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Darkwood Kitchen",
      "fileName": "kitchen-darkwood-remodel-03.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Dual Color/dual-color-kitchen-remodel-01.jpg",
      "alt": "Dual-Color Kitchen Custom kitchen remodel featuring dual color kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Dual-Color Kitchen",
      "fileName": "dual-color-kitchen-remodel-01.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Dual Color/dual-color-kitchen-remodel-02.jpg",
      "alt": "Dual-Color Kitchen Custom kitchen remodel featuring dual color kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Dual-Color Kitchen",
      "fileName": "dual-color-kitchen-remodel-02.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Dual Color/dual-color-kitchen-remodel-03.jpg",
      "alt": "Dual-Color Kitchen Custom kitchen remodel featuring dual color kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Dual-Color Kitchen",
      "fileName": "dual-color-kitchen-remodel-03.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Dual Color/dual-color-kitchen-remodel-04.jpg",
      "alt": "Dual-Color Kitchen Custom kitchen remodel featuring dual color kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Dual-Color Kitchen",
      "fileName": "dual-color-kitchen-remodel-04.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-01.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-01.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-02.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-02.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-03.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-03.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-04.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-04.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-05.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-05.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-06.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-06.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-07.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-07.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-08.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-08.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-09.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-09.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-10.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-10.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-11.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-11.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-12.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-12.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-13.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-13.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-14.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-14.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-15.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-15.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-16.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-16.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-17.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-17.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Kitchen Cabinet Refacing/kitchen-cabinet-remodel-refacing-18.jpg",
      "alt": "Kitchen Cabinet Refacing Custom kitchen remodel featuring kitchen cabinet remodel refacing by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Kitchen Cabinet Refacing",
      "fileName": "kitchen-cabinet-remodel-refacing-18.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Quartzite Remodel/white-luxury-kitchen-remodel-01.jpg",
      "alt": "Quartzite Luxury Kitchen Custom kitchen remodel featuring white luxury kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Quartzite Luxury Kitchen",
      "fileName": "white-luxury-kitchen-remodel-01.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Quartzite Remodel/white-luxury-kitchen-remodel-02.jpg",
      "alt": "Quartzite Luxury Kitchen Custom kitchen remodel featuring white luxury kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Quartzite Luxury Kitchen",
      "fileName": "white-luxury-kitchen-remodel-02.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Quartzite Remodel/white-luxury-kitchen-remodel-03.jpg",
      "alt": "Quartzite Luxury Kitchen Custom kitchen remodel featuring white luxury kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Quartzite Luxury Kitchen",
      "fileName": "white-luxury-kitchen-remodel-03.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Quartzite Remodel/white-luxury-kitchen-remodel-04.jpg",
      "alt": "Quartzite Luxury Kitchen Custom kitchen remodel featuring white luxury kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Quartzite Luxury Kitchen",
      "fileName": "white-luxury-kitchen-remodel-04.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Quartzite Remodel/white-luxury-kitchen-remodel-05.jpg",
      "alt": "Quartzite Luxury Kitchen Custom kitchen remodel featuring white luxury kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Quartzite Luxury Kitchen",
      "fileName": "white-luxury-kitchen-remodel-05.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Quartzite Remodel/white-luxury-kitchen-remodel-06.jpg",
      "alt": "Quartzite Luxury Kitchen Custom kitchen remodel featuring white luxury kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Quartzite Luxury Kitchen",
      "fileName": "white-luxury-kitchen-remodel-06.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Quartzite Remodel/white-luxury-kitchen-remodel-07.jpg",
      "alt": "Quartzite Luxury Kitchen Custom kitchen remodel featuring white luxury kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Quartzite Luxury Kitchen",
      "fileName": "white-luxury-kitchen-remodel-07.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Quartzite Remodel/white-luxury-kitchen-remodel-08.jpg",
      "alt": "Quartzite Luxury Kitchen Custom kitchen remodel featuring white luxury kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Quartzite Luxury Kitchen",
      "fileName": "white-luxury-kitchen-remodel-08.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-01.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-01.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-02.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-02.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-03.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-03.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-04.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-04.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-05.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-05.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-06.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-06.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-07.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-07.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-08.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-08.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-09.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-09.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-10.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-10.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-11.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-11.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-12.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-12.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-13.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-13.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-14.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-14.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-15.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-15.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-16.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-16.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/Vintage Kitchen/vintage-kitchen-remodel-white-17.jpg",
      "alt": "Vintage Kitchen Custom kitchen remodel featuring vintage kitchen remodel white by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "Vintage Kitchen",
      "fileName": "vintage-kitchen-remodel-white-17.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/kitchen-remodel-laurien-02.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring kitchen remodel laurien by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "kitchen-remodel-laurien-02.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/kitchen-remodel-laurien-03.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring kitchen remodel laurien by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "kitchen-remodel-laurien-03.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/kitchen-remodel-laurien-04.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring kitchen remodel laurien by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "kitchen-remodel-laurien-04.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/kitchen-remodel-laurien-05.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring kitchen remodel laurien by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "kitchen-remodel-laurien-05.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/kitchen-remodel-laurien-06.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring kitchen remodel laurien by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "kitchen-remodel-laurien-06.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/white-cabinet-kitchen-remodel-01.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring white cabinet kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "white-cabinet-kitchen-remodel-01.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/white-cabinet-kitchen-remodel-02.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring white cabinet kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "white-cabinet-kitchen-remodel-02.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/white-cabinet-kitchen-remodel-03.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring white cabinet kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "white-cabinet-kitchen-remodel-03.jpg"
    },
    {
      "src": "/images/gallery/kitchen remodel/White Cabinets/white-cabinet-kitchen-remodel-04.jpg",
      "alt": "White Cabinet Kitchen Custom kitchen remodel featuring white cabinet kitchen remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Kitchens",
      "project": "White Cabinet Kitchen",
      "fileName": "white-cabinet-kitchen-remodel-04.jpg"
    },
    {
      "src": "/images/gallery/white  bookcase remodel-01.jpg",
      "alt": "Custom built-in bookcase with white  bookcase remodel by Professional Wood Interiors - St. Louis, MO",
      "category": "Bookcases",
      "project": null,
      "fileName": "white  bookcase remodel-01.jpg"
    }
  ],
  "categories": [
    {
      "name": "Kitchens",
      "count": 68,
      "heroImage": "/images/gallery/kitchen remodel/Dual Color/dual-color-kitchen-remodel-01.jpg"
    },
    {
      "name": "Bedrooms",
      "count": 6,
      "heroImage": "/images/gallery/Bedroom/professional-wood-interiors-bedroom-remodel-01.png"
    },
    {
      "name": "Entertainment Centers",
      "count": 8,
      "heroImage": "/images/gallery/Entertainment Centers/entertainment-center-01.jpg"
    },
    {
      "name": "Bookcases",
      "count": 3,
      "heroImage": "/images/gallery/Bookcases/white  bookcase remodel-02.jpg"
    }
  ],
  "totalImages": 86,
  "generatedAt": "2026-01-16T22:15:29.057Z"
};

export default galleryManifest;
